---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: inventory

namespace: default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: grafana-provisioning-datasources
    files:
      - files/provisioning/datasources/postgres.yaml
      - files/provisioning/datasources/prometheus.yaml

configMapGenerator:
  - name: grafana-provisioning-dashboards
    files:
      - files/provisioning/dashboards/dashboard.yaml
  - name: grafana-dashboards
    files:
      - files/dashboards/inventory/inventory-aws.json
      - files/dashboards/inventory/inventory-gardener.json
      - files/dashboards/inventory/inventory-leaked-aws.json
      - files/dashboards/inventory/inventory-gcp.json
      - files/dashboards/inventory/inventory-gcp-leaked.json
      - files/dashboards/inventory/inventory-azure.json
      - files/dashboards/inventory/inventory-azure-leaked.json
      - files/dashboards/inventory/inventory-openstack.json
      - files/dashboards/inventory/inventory-leaked-openstack.json
      - files/dashboards/inventory/inventory-worker-gardener-tasks.json
      - files/dashboards/inventory/inventory-worker-azure-tasks.json
      - files/dashboards/inventory/inventory-worker-gcp-tasks.json
      - files/dashboards/inventory/inventory-worker-aws-tasks.json
      - files/dashboards/inventory/inventory-worker-odg-tasks.json
